repoURL: git@github.com:thomasasamba-bot/enterprise_gitops_platform.git
targetRevision: HEAD
services:
  frontend:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/frontend
    tag: latest
  auth-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/auth-service
    tag: 17f67197967f9d4edbf3acc2fe8ee4f839df7243
  product-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/product-service
    tag: latest
  order-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/order-service
    tag: latest
  payment-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/payment-service
    tag: latest
  notification-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/notification-service
    tag: latest
