repoURL: git@github.com:thomasasamba-bot/enterprise_gitops_platform.git
targetRevision: HEAD
services:
  frontend:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/frontend
    tag: 61c55dc359775a4a9e83574e36b222994224e216
  auth-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/auth-service
    tag: 61c55dc359775a4a9e83574e36b222994224e216
  product-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/product-service
    tag: 61c55dc359775a4a9e83574e36b222994224e216
  order-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/order-service
    tag: 61c55dc359775a4a9e83574e36b222994224e216
  payment-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/payment-service
    tag: 61c55dc359775a4a9e83574e36b222994224e216
  notification-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/notification-service
    tag: 61c55dc359775a4a9e83574e36b222994224e216
