repoURL: git@github.com:thomasasamba-bot/enterprise_gitops_platform.git
targetRevision: HEAD
services:
  frontend:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/frontend
    tag: latest
  auth-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/auth-service
    tag: 0bb9eede36df5b51cd8fc84339b37f040db80573
  product-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/product-service
    tag: 0bb9eede36df5b51cd8fc84339b37f040db80573
  order-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/order-service
    tag: 0bb9eede36df5b51cd8fc84339b37f040db80573
  payment-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/payment-service
    tag: 0bb9eede36df5b51cd8fc84339b37f040db80573
  notification-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/notification-service
    tag: 0bb9eede36df5b51cd8fc84339b37f040db80573
