repoURL: git@github.com:thomasasamba-bot/enterprise_gitops_platform.git
targetRevision: HEAD
services:
  frontend:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/frontend
    tag: fd21958dca75a044d53bece897ba3f944fee0498
  auth-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/auth-service
    tag: fd21958dca75a044d53bece897ba3f944fee0498
  product-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/product-service
    tag: fd21958dca75a044d53bece897ba3f944fee0498
  order-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/order-service
    tag: fd21958dca75a044d53bece897ba3f944fee0498
  payment-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/payment-service
    tag: fd21958dca75a044d53bece897ba3f944fee0498
  notification-service:
    path: gitops/charts/microservice
    namespace: default
    image: enterprise-gitops/notification-service
    tag: fd21958dca75a044d53bece897ba3f944fee0498
