{{- range $name, $config := .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: {{ $.Values.targetRevision }}
    path: {{ $config.path }}
    helm:
      values: |
        image:
          repository: {{ $config.image }}
          tag: {{ $config.tag }}
        fullnameOverride: {{ $name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $config.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
